// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hszgojxawrwsfagcianp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzemdvanhhd3J3c2ZhZ2NpYW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDU2MjUsImV4cCI6MjA3MTIyMTYyNX0.EKHG2MJ-l2w0Vw-rtmP9mMw6KiIZCFb_uU3aqxr-cZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});